### ISSUE TITLE
Recipe Book

### ISSUE THREAD

**Issue by XOR-SABER** [Af0n/CST438Proj3Group2#57]
We need no know what to make, and what ingredients we get

**Comment by Af0n** [comment]
- Calming Potion (Pure Water, Sparkling Apple)
- Healing Potion (Pure Water, Sparkling Ruby)
- Mana Potion (Salt, Ruby Dust, Coalesced Spirit)

**Comment by Af0n** [comment]
How to Get Items

Resource Nodes
- Fresh Apple: Apple Tree
- Raw Ruby: Ruby Ore
- Disordered Soul: Grave

Stations
- Washing Station
- - Sparkling Apple from Fresh Apple
- - Sparkling Ruby from Raw Ruby
- Conjuration Table
- - Saltwater from Bucket
- - Coalesced Spirit from Disordered Soul
- Conflagration Pyre
- - Salt from Saltwater
- - Fresh Water from Saltwater
- - Bucket from Water
- Grindstone
- - Ruby Dust from Sparkling Ruby

Currently no way to get more buckets

**Comment by Af0n** [comment]
oops didnt mean to do that
